// In-memory mock backend used when the Python/Supabase API is not running.
// Data lives for the lifetime of the dev server process and resets on restart.
// This mirrors the shapes returned by apps/api so the frontend works unchanged.

import type {
  ProvenanceEvent,
  ResearchObject,
  ResearchObjectCreate,
  Result,
  Run,
  RunCreate,
} from "@/lib/api/client";

type Store = {
  researchObjects: ResearchObject[];
  runs: Run[];
  provenance: ProvenanceEvent[];
  results: Result[];
};

const globalForStore = globalThis as unknown as { __casaiStore?: Store };

function buildMockFields(pdbId: string) {
  const id = pdbId.toLowerCase() || "unknown";
  return {
    mmcif_fetched_from: `https://files.rcsb.org/download/${pdbId || "UNKNOWN"}.cif`,
    mmcif_hash: "mock:mmcif_hash_placeholder",
    sequence_length: 1500,
    gc_content: 0.52,
    avg_phred_score: 35.0,
    reads_passing_qc: 980000,
    reads_total: 1000000,
    ro_hash: `sha256:mock_ro_hash_${id}`,
    status: "ready",
    fasta_preview:
      "ATGCGATCGGTACTAGTACGATCGGTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGC...",
  };
}

function seed(): Store {
  const created_at = new Date().toISOString();
  const ro: ResearchObject = {
    research_object_id: "ro_demo_0001",
    created_at,
    name: "Demo BRCA2 base-edit trial",
    input_filename: "casai_sample_input.fasta",
    input_file_type: "fasta",
    pdb_id: "1MJE",
    target_region: [720, 742],
    ...buildMockFields("1MJE"),
  };
  return { researchObjects: [ro], runs: [], provenance: [], results: [] };
}

function getStore(): Store {
  if (!globalForStore.__casaiStore) {
    globalForStore.__casaiStore = seed();
  }
  return globalForStore.__casaiStore;
}

function randomId(prefix: string): string {
  return `${prefix}_${Math.random().toString(36).slice(2, 10)}`;
}

// ─── Research Objects ───────────────────────────────────────────────────────

export function listResearchObjects(): ResearchObject[] {
  return getStore().researchObjects;
}

export function getResearchObject(id: string): ResearchObject | undefined {
  return getStore().researchObjects.find((r) => r.research_object_id === id);
}

export function createResearchObject(data: ResearchObjectCreate): ResearchObject {
  const store = getStore();
  const ro: ResearchObject = {
    research_object_id: randomId("ro"),
    created_at: new Date().toISOString(),
    name: data.name,
    input_filename: data.input_filename,
    input_file_type: data.input_file_type,
    pdb_id: data.pdb_id,
    target_region: data.target_region ?? [720, 742],
    ...buildMockFields(data.pdb_id),
  };
  store.researchObjects.unshift(ro);
  return ro;
}

// ─── Runs ─────────────────────────────────────────────────────────────────

export function listRuns(): Run[] {
  return getStore().runs;
}

export function getRun(id: string): Run | undefined {
  return getStore().runs.find((r) => r.run_id === id);
}

export function listRunsByResearchObject(researchObjectId: string): Run[] {
  return getStore().runs.filter((r) => r.research_object_id === researchObjectId);
}

export function createRun(data: RunCreate): Run {
  const store = getStore();
  const now = new Date().toISOString();
  const run: Run = {
    run_id: randomId("run"),
    research_object_id: data.research_object_id,
    created_at: now,
    prompt: data.prompt,
    status: "completed",
    started_at: now,
    completed_at: now,
    guide_rna: "GACGCCAAAACATATTTCTG",
    current_stage: "report",
  };
  store.runs.unshift(run);

  const stages = ["intake", "design", "simulate", "score", "report"];
  stages.forEach((stage, i) => {
    store.provenance.push({
      event_id: randomId("evt"),
      run_id: run.run_id,
      stage,
      event_type: "stage_completed",
      message: `Stage '${stage}' completed.`,
      payload: { index: i },
      duration_ms: 120 + i * 45,
      occurred_at: now,
    });
  });

  store.results.push({
    result_id: randomId("res"),
    run_id: run.run_id,
    research_object_id: data.research_object_id,
    edited_sequence: "ATGC...GACGCCAAAACATATTTCTG...TGAC",
    edit_summary: "Single base edit applied at target region 720-742.",
    off_target_score: 0.03,
    on_target_score: 0.94,
    notes: "Mock result generated by the local in-memory backend.",
    reproducible: true,
  });

  return run;
}

// ─── Provenance & Results ───────────────────────────────────────────────────

export function listProvenance(runId: string): ProvenanceEvent[] {
  return getStore().provenance.filter((e) => e.run_id === runId);
}

export function listResults(runId: string): Result[] {
  return getStore().results.filter((r) => r.run_id === runId);
}
